services:
  # http://127.0.0.1:80
  flask_server:
    image: timbsm/translator:latest
    container_name: flask_server
    ports:
      - "80:5000"
    restart: always
    env_file: ".env"
    environment:
      # Others
      TZ: Europe/Berlin

      # Azure Translator
      TRANSLATOR_AZURE_TEXT_TRANSLATION_APIKEY: ${TRANSLATOR_AZURE_TEXT_TRANSLATION_APIKEY}
      TRANSLATOR_AZURE_TEXT_TRANSLATION_REGION: ${TRANSLATOR_AZURE_TEXT_TRANSLATION_REGION}

      # MongoDB
      TRANSLATOR_MONGODB_URI: ${TRANSLATOR_MONGODB_URI}
