# The following commands can be used to start up the programm.
#
# $ docker compose up -d --watch --build
# -> -d is optional to start the container as daemon (in the back-
#    ground)
# -> --watch is optional to reflect any local changes in the container
# -> --build is optional to rebuild the images
#
# $ docker compose stop
# $ docker compose down
# -> stop or delete the containers
#
# $ docker ps -a -q
# -> show every running docker container
# -> -a is optional to show not running ones as well
# -> -q only show the ids of the containers

services:
  # http://127.0.0.1:80
  flask_server:
    container_name: flask_server
    build:
      context: ./src
      args:
        # Linux
        UID: 1001
        GID: 1001
    develop:
      watch:
        - action: sync
          path: ./src
          target: /home/nonroot/app
          ignore:
            - .dockerignore
            - Dockerfile
            - requirements.txt
    ports:
      - "80:5000"
    restart: always
    env_file: ".env"
    environment:
      # Others
      TZ: Europe/Berlin
